In [167]:


import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

from nhs_waiting_lists.constants import proj_db_path
from nhs_waiting_lists.utils.proj_paths import find_project_root

project_root = find_project_root()

DB_PATH = project_root / proj_db_path / "nhs_rttwtd.db"
DATA_DIR = "./data"

conn = create_engine(f"sqlite:///{DB_PATH}")

In [168]:

from nhs_waiting_lists.utils.utils2 import last_full_quarter

print(last_full_quarter("2025-7"))

(2025, 2)

In [169]:


query = text("""
             SELECT *
             from v_consolidated; \
             """).bindparams(
    # bindparam('provider_codes', expanding=True),
    # bindparam('treatment_codes', expanding=True)
)

df = pd.read_sql(
    query, conn, params={  # type: ignore[arg-type]
        # 'provider_codes': PROVIDER_CODES,
    }
)

providers = pd.read_sql("""
                        SELECT DISTINCT provider_code AS provider, provider_name
                        FROM providers
                        """, conn, params={  # type: ignore[arg-type]
    # 'provider_codes': PROVIDER_CODES,
})

# df.query("provider == 'RAJ' and treatment == 'C_999' and period == '2025-08'")
df

,period,provider_name,subtype,Quarter,provider,treatment,incomplete,admitted,nonadmitted,new_periods,incomplete_prev,wait_pct_lt_18
0,2021-05,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,2,R0B,C_999,38116,2469,10814,17215,NaN,0.875669
1,2021-06,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,2,R0B,C_999,40317,2772,11371,18622,38116.0,0.881812
2,2021-07,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,3,R0B,C_999,43170,2420,10116,17791,40317.0,0.869099
3,2021-08,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,3,R0B,C_999,43946,2356,8898,15761,43170.0,0.856528
4,2021-09,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,3,R0B,C_999,45349,2790,10123,18007,43946.0,0.844848
...,...,...,...,...,...,...,...,...,...,...,...,...
1186,2025-04,East Lancashire Hospitals NHS Trust,Acute - Large,2,RXR,C_999,60237,1755,7215,11017,60809.0,0.564620
1187,2025-05,East Lancashire Hospitals NHS Trust,Acute - Large,2,RXR,C_999,57660,2012,7897,11771,60237.0,0.584287
1188,2025-06,East Lancashire Hospitals NHS Trust,Acute - Large,2,RXR,C_999,58192,2172,8484,13750,57660.0,0.606853
1189,2025-07,East Lancashire Hospitals NHS Trust,Acute - Large,3,RXR,C_999,57371,2368,8695,14741,58192.0,0.611685
1190,2025-08,East Lancashire Hospitals NHS Trust,Acute - Large,3,RXR,C_999,57217,1898,8269,12690,57371.0,0.601167

In [170]:
import pandas as pd

dt_recent = pd.read_sql("""
                        SELECT MAX(period) as period
                        FROM consolidated
                        """, conn, params={  # type: ignore[arg-type]
})

print(last_full_quarter(dt_recent["period"].iloc[0]))

(2025, 2)

In [171]:
from nhs_waiting_lists.utils.utils2 import last_n_full_quarters

full_quarters = last_n_full_quarters(dt_recent["period"].iloc[0])
full_quarters

[(2024, 4), (2025, 1), (2025, 2)]

In [172]:
# unique years in the quarters
years = list(set([x[0] for x in full_quarters]))
years

[2024, 2025]

In [173]:


# extract year + quarter
df["year"] = df["period"].str[:4].astype(int)
df["month"] = df["period"].str[5:7].astype(int)
df["quarter"] = df['year'].astype(str) + '-q' + ((df['month'] - 1) // 3 + 1).astype(str)

# df["quarter"] = f"{df['year']}-{((df['month'] - 1) // 3) + 1}"

df

,period,provider_name,subtype,Quarter,provider,treatment,incomplete,admitted,nonadmitted,new_periods,incomplete_prev,wait_pct_lt_18,year,month,quarter
0,2021-05,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,2,R0B,C_999,38116,2469,10814,17215,NaN,0.875669,2021,5,2021-q2
1,2021-06,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,2,R0B,C_999,40317,2772,11371,18622,38116.0,0.881812,2021,6,2021-q2
2,2021-07,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,3,R0B,C_999,43170,2420,10116,17791,40317.0,0.869099,2021,7,2021-q3
3,2021-08,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,3,R0B,C_999,43946,2356,8898,15761,43170.0,0.856528,2021,8,2021-q3
4,2021-09,South Tyneside and Sunderland NHS Foundation T...,Acute - Large,3,R0B,C_999,45349,2790,10123,18007,43946.0,0.844848,2021,9,2021-q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186,2025-04,East Lancashire Hospitals NHS Trust,Acute - Large,2,RXR,C_999,60237,1755,7215,11017,60809.0,0.564620,2025,4,2025-q2
1187,2025-05,East Lancashire Hospitals NHS Trust,Acute - Large,2,RXR,C_999,57660,2012,7897,11771,60237.0,0.584287,2025,5,2025-q2
1188,2025-06,East Lancashire Hospitals NHS Trust,Acute - Large,2,RXR,C_999,58192,2172,8484,13750,57660.0,0.606853,2025,6,2025-q2
1189,2025-07,East Lancashire Hospitals NHS Trust,Acute - Large,3,RXR,C_999,57371,2368,8695,14741,58192.0,0.611685,2025,7,2025-q3
1190,2025-08,East Lancashire Hospitals NHS Trust,Acute - Large,3,RXR,C_999,57217,1898,8269,12690,57371.0,0.601167,2025,8,2025-q3

In [174]:

# average by provider/year/quarter
q = (
    df.groupby(["provider", "quarter"])["wait_pct_lt_18"]
    .mean()
    .reset_index()
)
q = q[q['quarter'].isin([f"{year}-q{quarter}" for year, quarter in full_quarters])]
q

# q['quarter'].isin([f"{year}-q{quarter}" for year, quarter in full_quarters])]

    provider  quarter  wait_pct_lt_18
14       R0B  2024-q4        0.746413
15       R0B  2025-q1        0.751532
16       R0B  2025-q2        0.754843
32       RAJ  2024-q4        0.521804
33       RAJ  2025-q1        0.502486
..       ...      ...             ...
392      RXK  2025-q1        0.537904
393      RXK  2025-q2        0.565630
409      RXR  2024-q4        0.570337
410      RXR  2025-q1        0.573669
411      RXR  2025-q2        0.585253

[69 rows x 3 columns]

In [175]:

# pivot to quarters as columns
pivot = q.pivot(index="provider", columns=["quarter"], values="wait_pct_lt_18")
pivot

quarter    2024-q4   2025-q1   2025-q2
provider
R0B       0.746413  0.751532  0.754843
RAJ       0.521804  0.502486  0.492790
RDE       0.549499  0.551230  0.560531
RDU       0.510425  0.516470  0.550233
REF       0.686029  0.688836  0.711441
RGN       0.524479  0.527045  0.534518
RH8       0.580356  0.599191  0.603163
RHU       0.542113  0.534613  0.554693
RHW       0.814172  0.779011  0.786013
RJ2       0.565563  0.570504  0.563829
RL4       0.527982  0.512908  0.539640
RN5       0.579802  0.585743  0.591612
RTE       0.663374  0.684176  0.688187
RTF       0.799731  0.793857  0.805277
RVJ       0.663265  0.652933  0.645495
RWD       0.527323  0.536184  0.541939
RWF       0.707251  0.728456  0.725124
RWH       0.593202  0.621497  0.629764
RWP       0.563262  0.575676  0.596651
RWY       0.694687  0.690400  0.685887
RXC       0.542814  0.564946  0.617958
RXK       0.532740  0.537904  0.565630
RXR       0.570337  0.573669  0.585253

In [176]:

# pivot.columns = [f"2024-Q{c}" for c in pivot.columns]

# compute trend vs 3 quarters earlier (or 2 here)
pivot["trend_delta"] = pivot.iloc[:, 0] - pivot.iloc[:, 2]
pivot

quarter    2024-q4   2025-q1   2025-q2  trend_delta
provider
R0B       0.746413  0.751532  0.754843    -0.008430
RAJ       0.521804  0.502486  0.492790     0.029014
RDE       0.549499  0.551230  0.560531    -0.011032
RDU       0.510425  0.516470  0.550233    -0.039808
REF       0.686029  0.688836  0.711441    -0.025413
RGN       0.524479  0.527045  0.534518    -0.010039
RH8       0.580356  0.599191  0.603163    -0.022807
RHU       0.542113  0.534613  0.554693    -0.012580
RHW       0.814172  0.779011  0.786013     0.028159
RJ2       0.565563  0.570504  0.563829     0.001734
RL4       0.527982  0.512908  0.539640    -0.011658
RN5       0.579802  0.585743  0.591612    -0.011810
RTE       0.663374  0.684176  0.688187    -0.024813
RTF       0.799731  0.793857  0.805277    -0.005546
RVJ       0.663265  0.652933  0.645495     0.017770
RWD       0.527323  0.536184  0.541939    -0.014617
RWF       0.707251  0.728456  0.725124    -0.017873
RWH       0.593202  0.621497  0.629764    -0.036562
RWP       0.563262  0.575676  0.596651    -0.033389
RWY       0.694687  0.690400  0.685887     0.008800
RXC       0.542814  0.564946  0.617958    -0.075144
RXK       0.532740  0.537904  0.565630    -0.032890
RXR       0.570337  0.573669  0.585253    -0.014916

In [ ]:

pivot["Trend"] = pd.cut(
    pivot["trend_delta"],
    bins=[-1, -0.01, 0.01, 1],
    labels=["↓ Declining", "→ Stable", "↑ Improving"]
)

# format as percent
for col in range(3):
    pivot[f"col_{col}"] = (pivot.iloc[:, col] * 100).round(1).astype(str) + "%"

pivot = pivot.reset_index()

In [178]:

wide_df = pd.merge(pivot, providers, on='provider', how='inner')

print(wide_df)

   provider   2024-q4   2025-q1   2025-q2  trend_delta        Trend  col_0  \
0       R0B  0.746413  0.751532  0.754843    -0.008430     → Stable  74.6%
1       RAJ  0.521804  0.502486  0.492790     0.029014  ↑ Improving  52.2%
2       RDE  0.549499  0.551230  0.560531    -0.011032  ↓ Declining  54.9%
3       RDU  0.510425  0.516470  0.550233    -0.039808  ↓ Declining  51.0%
4       REF  0.686029  0.688836  0.711441    -0.025413  ↓ Declining  68.6%
5       RGN  0.524479  0.527045  0.534518    -0.010039  ↓ Declining  52.4%
6       RH8  0.580356  0.599191  0.603163    -0.022807  ↓ Declining  58.0%
7       RHU  0.542113  0.534613  0.554693    -0.012580  ↓ Declining  54.2%
8       RHW  0.814172  0.779011  0.786013     0.028159  ↑ Improving  81.4%
9       RJ2  0.565563  0.570504  0.563829     0.001734     → Stable  56.6%
10      RL4  0.527982  0.512908  0.539640    -0.011658  ↓ Declining  52.8%
11      RN5  0.579802  0.585743  0.591612    -0.011810  ↓ Declining  58.0%
12      RTE  0.663374  0.684176  0.688187    -0.024813  ↓ Declining  66.3%
13      RTF  0.799731  0.793857  0.805277    -0.005546     → Stable  80.0%
14      RVJ  0.663265  0.652933  0.645495     0.017770  ↑ Improving  66.3%
15      RWD  0.527323  0.536184  0.541939    -0.014617  ↓ Declining  52.7%
16      RWF  0.707251  0.728456  0.725124    -0.017873  ↓ Declining  70.7%
17      RWH  0.593202  0.621497  0.629764    -0.036562  ↓ Declining  59.3%
18      RWP  0.563262  0.575676  0.596651    -0.033389  ↓ Declining  56.3%
19      RWY  0.694687  0.690400  0.685887     0.008800     → Stable  69.5%
20      RXC  0.542814  0.564946  0.617958    -0.075144  ↓ Declining  54.3%
21      RXK  0.532740  0.537904  0.565630    -0.032890  ↓ Declining  53.3%
22      RXR  0.570337  0.573669  0.585253    -0.014916  ↓ Declining  57.0%

    col_1  col_2                                      provider_name
0   75.2%  75.5%  South Tyneside and Sunderland NHS Foundation T...
1   50.2%  49.3%           Mid and South Essex NHS Foundation Trust
2   55.1%  56.1%  East Suffolk and North Essex NHS Foundation Trust
3   51.6%  55.0%                Frimley Health NHS Foundation Trust
4   68.9%  71.1%                 Royal Cornwall Hospitals NHS Trust
5   52.7%  53.5%             North West Anglia NHS Foundation Trust
6   59.9%  60.3%  Royal Devon University Healthcare NHS Foundati...
7   53.5%  55.5%  Portsmouth Hospitals University National Healt...
8   77.9%  78.6%               Royal Berkshire NHS Foundation Trust
9   57.1%  56.4%                   Lewisham and Greenwich NHS Trust
10  51.3%  54.0%                  The Royal Wolverhampton NHS Trust
11  58.6%  59.2%           Hampshire Hospitals NHS Foundation Trust
12  68.4%  68.8%     Gloucestershire Hospitals NHS Foundation Trust
13  79.4%  80.5%        Northumbria Healthcare NHS Foundation Trust
14  65.3%  64.5%                            North Bristol NHS Trust
15  53.6%  54.2%            United Lincolnshire Hospitals NHS Trust
16  72.8%  72.5%            Maidstone and Tunbridge Wells NHS Trust
17  62.1%  63.0%             East and North Hertfordshire NHS Trust
18  57.6%  59.7%           Worcestershire Acute Hospitals NHS Trust
19  69.0%  68.6%   Calderdale and Huddersfield NHS Foundation Trust
20  56.5%  61.8%                   East Sussex Healthcare NHS Trust
21  53.8%  56.6%   Sandwell and West Birmingham Hospitals NHS Trust
22  57.4%  58.5%                East Lancashire Hospitals NHS Trust